name: Ping API

on:
  schedule:
    - cron: '0 12 * * *' # Runs every day at 12 PM UTC

jobs:
  ping:
    runs-on: windows-latest
    steps:
      - name: Ping API
        run: |
          Invoke-WebRequest -Uri https://vege-api-2ao6.vercel.app/ -Method Get
